# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib meftools
#' @param StringVector strings
#' @export
decomp_mef <- function(strings) {
    .Call('_meftools_decomp_mef', PACKAGE = 'meftools', strings)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib meftools
#' @param StringVector strings
#' @param NumericMatrix ToC
#' @export
get_discontinuities <- function(strings, ToC) {
    .Call('_meftools_get_discontinuities', PACKAGE = 'meftools', strings, ToC)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib meftools
#' @export
ncs2mef <- function(strings) {
    .Call('_meftools_ncs2mef', PACKAGE = 'meftools', strings)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib meftools
#' @param StringVector strings
#' @export
read_mef_header <- function(strings) {
    .Call('_meftools_read_mef_header', PACKAGE = 'meftools', strings)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib meftools
#' @param StringVector strings
#' @export
table_of_contents <- function(strings) {
    .Call('_meftools_table_of_contents', PACKAGE = 'meftools', strings)
}

